accelerator: null
accumulate_grad_batches: null
amp_backend: null
amp_level: null
audio_dir: /home/kieran/Level5ProjectAudioVAE/src/audio
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 8
benchmark: null
buffer_reload_rate: 1000
buffer_size_gb: 1.0
check_val_every_n_epoch: 1
conv_kernel: 3
conv_padding: 1
conv_stride: 2
dafx_file: /home/kieran/Level5ProjectAudioVAE/src/dafx/mda.vst3
dafx_names:
- mda Overdrive
- mda Delay
- mda Dynamics
- mda RingMod
dafx_param_names: null
default_root_dir: null
detect_anomaly: false
devices: null
dsp_sample_rate: 24000
dummy_setting: false
effect_input: false
effect_output: true
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
ext: wav
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
half: false
hidden_dim: !!python/tuple
- 32
- 5
- 129
hop_length: 2048
inference_mode: true
input_dirs:
- vctk_24000
ipus: null
latent_dim: 4096
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
lr: 0.0001
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_fft: 4096
normalise_audio: true
num_channels: 2
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 4
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
random_effect_threshold: 0.75
recon_loss: mse
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
return_phase: false
sample_rate: 24000
shuffle: true
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
train_examples_per_epoch: 5000
train_frac: 0.9
train_length: 131072
vae_beta: 0.005
val_check_interval: null
val_examples_per_epoch: 500
val_length: 131072
window_size: 4096
