accelerator: null
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 256
benchmark: null
check_val_every_n_epoch: 1
commitment_cost: 0.25
decay: 0.99
default_root_dir: null
detect_anomaly: false
devices: null
embedding_dim: 64
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
inference_mode: true
ipus: null
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
lr: 0.001
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_embeddings: 512
num_hiddens: 128
num_nodes: 1
num_processes: null
num_residual_hiddens: 32
num_residual_layers: 2
num_sanity_val_steps: 2
num_workers: 4
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
val_check_interval: null
