accelerator: null
accumulate_grad_batches: null
amp_backend: null
amp_level: null
audio_dir: /home/kieran/Level5ProjectAudioVAE/src/audio
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 16
benchmark: null
buffer_reload_rate: 1000
buffer_size_gb: 1.0
check_val_every_n_epoch: 1
commitment_cost: 0.25
dafx_file: /home/kieran/Level5ProjectAudioVAE/src/dafx/mda.vst3
dafx_names:
- mda MultiBand
- mda Delay
- mda Overdrive
- mda RingMod
- mda Thru-Zero Flanger
dafx_param_names: null
decay: 0.99
default_root_dir: null
detect_anomaly: false
devices: null
dsp_sample_rate: 24000
dummy_setting: false
effect_audio: true
embedding_dim: 4
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
ext: wav
f_max: 16000
f_min: 20
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
half: false
inference_mode: true
input_dirs:
- vctk_24000
ipus: null
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
lr: 0.0005
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_fft: 4096
n_mels: 256
num_embeddings: 4096
num_hiddens: 16
num_nodes: 1
num_processes: null
num_residual_hiddens: 8
num_residual_layers: 4
num_sanity_val_steps: 2
num_workers: 8
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
random_effect_threshold: 0.0
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sample_rate: 24000
shuffle: true
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
train_examples_per_epoch: 5000
train_frac: 0.9
train_length: 130560
val_check_interval: null
val_examples_per_epoch: 500
val_length: 130560
win_length: 1024
